profiles:
  include:
    - API-KEY

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-OAUTH-CLIENT-ID}
            client-secret: ${GOOGLE-OAUTH-SECRET}
            scope: profile, email