spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classmate
    username: ${MYSQL-USERNAME}
    password: ${MYSQL-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  profiles:
    include:
      - API-KEY
      - jwt
      - oauth

logging.level:
  org.hibernate.SQL: debug
